version: '3.9'
services:
  react:
    container_name: react_front
    build: .
    ports:
      - 7000:7000
    volumes:
      - './:/app'
      - '/app/node_modules'
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
